[package]
name = "fusen-register"
version = "0.8.3"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true


[dependencies]
fusen-internal-common.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
