[package]
name = "fusen-internal-common"
version = "0.8.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true


[dependencies]
thiserror.workspace = true