[package]
name = "fusen-derive-macro"
version = "0.8.5"
authors.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true


[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.71", features = ["full"] }